server:
    port: 8082
spring:
    application:
        name: movie
eureka:
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://eurekaserver:8761/eureka/
